### ISSUE TITLE
Serialization

### ISSUE THREAD

**Issue by kariminf** [assem-ch/assem-address-book#1]
I read the code rapidly, so I don't know for sure if this functionality exists, or if it is handled by another module or project dependent to this one.

Any address-book have to serialize the data somehow: in XML file, JSON file, sqlite database, etc. So I guess it will be useful to add this functionality.

**Comment by assem-ch** [comment]
This is just a work assignment for  a job position , so I only did requested features explained here: [Assignment](https://github.com/assem-ch/assem-address-book/blob/master/ASSIGNMENT.rst)

**Comment by kariminf** [comment]
Ah! OK
